#pragma kernel CSMain

static const int threadGroupSize = 1024;

struct Boid
{
    float3 position;
    float3 direction;

    float3 alignmentForce;
    float3 cohesionForce;
    float3 seperationForce;
    int numFlockmates;
    
    float viewRadius;
    float viewAngle;
    float separationRange;
    
    int boidType;
};

RWStructuredBuffer<Boid> boids;
uint _BoidCount;

[numthreads(threadGroupSize, 1, 1)]
void CSMain(uint3 id : SV_DispatchThreadID)
{

    Boid currentBoid = boids[id.x];

    for (uint j = 0; j < _BoidCount; j++)
    {
        if (id.x == j) continue;

        Boid other = boids[j];
        float3 offset = currentBoid.position - other.position;
        float dist = length(offset);

        if (dist == 0 || dist > currentBoid.viewRadius)
            continue;

        float angle = degrees(acos(dot(normalize(currentBoid.direction), normalize(offset))));
        if (angle > currentBoid.viewAngle * 0.5f)
            continue;
        
        //if (currentBoid.boidType != other.boidType)
           // continue;

        currentBoid.numFlockmates += 1;

        if (dist <= currentBoid.separationRange)
            currentBoid.seperationForce += normalize(offset) / dist;

        currentBoid.alignmentForce += normalize(other.direction);

        currentBoid.cohesionForce += other.position;
    }
    
    boids[id.x] = currentBoid;
}